### ISSUE TITLE
some videos are no longer available 

### ISSUE THREAD

**Issue by zhuqiangLu** [THUDM/LVBench#2]
Hi, 

Thank you for collecting this amazing long video dataset.

I noticed that there are 5 videos are no longer available:

```
idZkam9zqAs
aJI8XTa_DII
IsdbCjlZ5cQ
5dZ_lvDgevk
EpMLAQbSYAw
```

Are there alternative links for these videos?

**Comment by huangshiyu13** [comment]
It seems [5dZ_lvDgevk](https://www.youtube.com/watch?v=5dZ_lvDgevk) is available.

Sometimes, videos on YouTube might be taken down, and in such cases, these videos will have to be removed from LVBench.

**Comment by LiuRicky** [comment]
Up to Nov. 25th, the following videos are invalid:
```bash
idZkam9zqAs
Z4HGQL_McDQ
QWXlvx1GoTY
28CIeC8cZks
t-RtDI2RWQs
qYMnM5blZIE
gXnhqF0TqqI
QgWRyDV9Ozs
```
