### ISSUE TITLE
Evaluation Details

### ISSUE THREAD

**Issue by spidercatfly** [THUDM/LVBench#4]
Hi:
Thanks for your work! High-quality dataset!
Could you provide some details on the how you evaluated the model in your experiments, such as whether long videos need to be split into chunks, and whether speech and subtitles are extracted?

**Comment by huangshiyu13** [comment]
The whole video is input to the model. No speech and subtitles are used.

**Comment by spidercatfly** [comment]
Does this mean that a football match video of nearly two hours long can be fed into MLLMs such as LLaMA-VID, GPT-4o, LLaVA-NeXT at once?

**Comment by huangshiyu13** [comment]
> Does this mean that a football match video of nearly two hours long can be fed into MLLMs such as LLaMA-VID, GPT-4o, LLaVA-NeXT at once?

You are right.
